"""Created Category model with relationship with User.

Revision ID: a5488afa3579
Revises: b97b37e9f254
Create Date: 2024-04-22 13:50:39.755682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5488afa3579'
down_revision: Union[str, None] = 'b97b37e9f254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
        sa.Column('uuid', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('type', sa.Enum('income', 'expense', name='categorytype'), nullable=False),
        sa.Column('creator_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['users.uuid'], ),
        sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
