"""Created Record model with dependencies (User, Account, Category).

Revision ID: 8aa479995285
Revises: 105be7fbf0ca
Create Date: 2024-04-27 14:15:28.390976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa479995285'
down_revision: Union[str, None] = '105be7fbf0ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
        sa.Column('uuid', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('income', 'expense', name='recordtype'), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('creator_id', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('category_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.uuid'], ),
        sa.ForeignKeyConstraint(['category_id'], ['categories.uuid'], ),
        sa.ForeignKeyConstraint(['creator_id'], ['users.uuid'], ),
        sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
