"""Removed Category type field.

Revision ID: 105be7fbf0ca
Revises: a5488afa3579
Create Date: 2024-04-26 21:26:06.968907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '105be7fbf0ca'
down_revision: Union[str, None] = 'a5488afa3579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', postgresql.ENUM('income', 'expense', name='categorytype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
