"""Created Account model with relationship.

Revision ID: b97b37e9f254
Revises: 0d3d3bf1569f
Create Date: 2024-04-17 21:52:06.560779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97b37e9f254'
down_revision: Union[str, None] = '0d3d3bf1569f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
        sa.Column('uuid', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('creator_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_private', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['creator_id'], ['users.uuid'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
