from services import BaseService


class UserService(BaseService):
    def create_user(self): ...

    def get_user_by_uuid(self): ...

    def get_user_by_username(self): ...

    def get_user_by_email(self): ...
